In [1]:
import numpy as np

$$y=Ax$$

In [2]:
A = np.array([[1, 3]])  
x = np.array([[2], 
              [4]])     
y = A.dot(x)           
print(y)

[[14]]


In [3]:
v = np.array([[1], 
              [0], 
              [2], 
              [5], 
              [-2]])


w = np.array([[2], 
              [8], 
              [-6], 
              [1], 
              [0]])

print(v.T.dot(w))
print(v.dot(w.T))

[[-5]]
[[  2   8  -6   1   0]
 [  0   0   0   0   0]
 [  4  16 -12   2   0]
 [ 10  40 -30   5   0]
 [ -4 -16  12  -2   0]]


In [4]:
v = np.array([1, 0, 2, 5, -2])
w = np.array([2, 8, -6, 1, 0])

print(np.dot(v, w))

a = np.dot(v.T, w)

-5


In [5]:
# manual
res = 0
for i in range(len(v)):
    res += (v[i] * w[i])
print(res)

-5


In [58]:
# 2d matrix
v = np.array([[1, 0, 2, 5, -2]])
w = np.array([[2, 8, -6, 1, 0]])

np.dot(v.T, w)

array([[  2,   8,  -6,   1,   0],
       [  0,   0,   0,   0,   0],
       [  4,  16, -12,   2,   0],
       [ 10,  40, -30,   5,   0],
       [ -4, -16,  12,  -2,   0]])