Suppose: $$f(x,y,z)=(x + y)z$$

We can have: $$f(x) = zx$$ $$g(x) = x + y$$

Therefore: $$\frac{\partial{f}}{\partial{g}} = z ~,~ \frac{\partial{f}}{\partial{z}} = x + y ~,~ \frac{\partial{g}}{\partial{x}} = \frac{\partial{g}}{\partial{y}} = 1$$

In [6]:
import numpy as np

W = np.array([
    [3, 2, 1, -1],
    [2, 1, 3, 2],
    [3, 2, 1, -2]
])

dl_dy = np.array([
    [2, 3, -3, 9],
    [-8, 1, 4, 6]
])

W_transpose = W.transpose()
print(W_transpose)
print(dl_dy.dot(W_transpose))

[[ 3  2  3]
 [ 2  1  2]
 [ 1  3  1]
 [-1  2 -2]]
[[  0  16  -9]
 [-24   9 -30]]
